name: flutter_native_screenshot
description: A Flutter plugin to take screenshot on Android & iOS with natively code.
version: 1.1.1
homepage: https://github.com/Nusanet-Developers/flutter-native-screenshot
repository: https://github.com/Nusanet-Developers/flutter-native-screenshot.git
issue_tracker: https://github.com/Nusanet-Developers/flutter-native-screenshot/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: net.bengkelrobot.flutter_native_screenshot
        pluginClass: FlutterNativeScreenshotPlugin
      ios:
        pluginClass: FlutterNativeScreenshotPlugin
